In [1]:
Name= 'Catherine Bui'
Organization= 'Center For Community Innovation'
Project= 'Twitter Displacement Study'

In [ ]:
%%time
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import subprocess
from pathlib import Path
import csv
import xlrd
import numpy as np
import dask.dataframe as das
import sqlite3
import datetime

### READING THE CSV FILE 
1. Clean and prepare the data

In [2]:
%%time
file = "/scratch/public/catherinebui/sf_with_homeloc_one_tweet_per_day.csv"
rawfile = "/scratch/public/catherinebui/sf_with_homeloc.csv"
df = das.read_csv(rawfile)
df = df.rename(columns = {'sf_with_homeloc.csv': 'id'})

CPU times: user 3min 5s, sys: 24.3 s, total: 3min 29s
Wall time: 3min 30s

In [5]:
#Dropping Nan values
df=df.dropna(subset = ['home_tract'])
df = df.dropna(subset= ['tract'])
df['tract'] = df['tract'].astype('int')
df['home_tract'] = df['home_tract'].astype('int')

## Creating the neighbor binary variable for each tweet

In [6]:
#Creating a map of neigbhors to the source tract
sf_nn = pd.read_csv('sfbay_13county_nearest_neigbbor_new.csv')
def neighbors(src):
    for i in sf_nn['SRC_GEOID'].unique():
        if i == src:
            table=sf_nn[sf_nn['SRC_GEOID'] == i]
            return np.array(table['NBR_GEOID'])
    return []
n_ = []
for i in sf_nn['SRC_GEOID'].unique():
    n_.append(neighbors(i))
nn = pd.DataFrame(sf_nn['SRC_GEOID'].unique()) 
nn['neighbors'] = n_
nn = nn.rename(columns = {0: 'SRC_GEOID'})
neighbormap = dict(zip(nn['SRC_GEOID'], nn['neighbors']))

#Function that adds a 1 or 0 to each tweet if a tract is a neighbor or not of home_tract
def neighbor_check(x):
    if np.any(neighbormap.get(x['home_tract']) != None): 
        if x['tract'] in neighbormap.get(x['home_tract']):
            return 1
        else:
            return 0
    else:
        return 2
#Applying the neighbor_check to the dataframe
df['neighbor'] = df.apply(lambda x: neighbor_check(x), axis = 1, meta = 'float64')
df= df[(df["tract"].isin(neighbormap.keys())) & (df["home_tract"].isin(neighbormap.keys()))]
#creating the non-neighbor table
other = df[(df['neighbor'] == 0) & (df['tract'] != df['home_tract'])]

In [21]:
#total tweets in each tract BEFORE MERGING WITH DEMOGRAPHIC VARIABLES
other.groupby(['tract']).aggregate({'id': 'count'}).reset_index().to_csv('newnn2_bayarea_totaltweets_*.csv')

['newnn2_bayarea_totaltweets_0.csv']

In [43]:
#DEMOGRAPHIC VARIABLES OF BAY AREA
demo_var = pd.read_csv('home_tract_variables.csv')
demo_var = demo_var.rename(
    columns = {'geo_fips': 'home_tract'})

In [46]:
#Joining the non-neighbor table with the home tract variables csv (demo_var)
other = other.merge(demo_var, on = 'home_tract', how = 'inner')

In [99]:
#Testing total tweets in each tract after Merge
other.groupby(['tract']).aggregate({'id': 'count'}).reset_index().to_csv('new_nn_bayarea_totaltweets_*.csv')

['new_nn_bayarea_totaltweets_0.csv']

In [100]:
#Counting total neighbor tweets in each tract after Merge
df[df['neighbor'] == 1].groupby(['tract']).aggregate({'id': 'count'}).reset_index().to_csv('neighborbayarea_totaltweets_*.csv')

['neighborbayarea_totaltweets_0.csv']

In [ ]:
#Counting total local tweets in each tract after Merge
df[df['home_tract'] == df['tract']].groupby(['tract']).aggregate({'id': 'count'}).reset_index().to_csv('localbayarea_totaltweets_*.csv')

## Aggregation: 
Creating csv files for all the numbers and percentages of tweets sent from non-neighbor users in a tract with specific demographic characteristics.

In [47]:
%%time
#aboverm_per_col15
aboverm_per_col15 = other.groupby(['tract', 'aboverm_per_col15']).aggregate(
    {'u_id': 'count'}).reset_index()
aboverm_per_col15 = aboverm_per_col15.categorize(columns = 'aboverm_per_col15')
aboverm_per_col15 = aboverm_per_col15.pivot_table(values = 'u_id',
                                                 columns = 'aboverm_per_col15', 
                                                 index = 'tract')

CPU times: user 56min 18s, sys: 4min 28s, total: 1h 47s
Wall time: 54min 4s

In [48]:
#Function to take the variable and return the csv of the counts of non-neighbor tweets with that condition
def create_csv(demo_variable):
    g = other.groupby(['tract', demo_variable]).aggregate(
        {'u_id': 'count'}).reset_index()
    g = g.categorize(columns = demo_variable)
    g = g.pivot_table(values = 'u_id',
                      columns = demo_variable, 
                      index = 'tract')
    g.to_csv(demo_variable + '_*.csv')

In [49]:
%%time
create_csv('aboverm_per_nonwhite15')

CPU times: user 1h 52min 31s, sys: 8min 37s, total: 2h 1min 9s
Wall time: 1h 48min 3s

In [50]:
%%time
create_csv('aboverm_empd14')

CPU times: user 1h 51min 14s, sys: 8min 5s, total: 1h 59min 19s
Wall time: 1h 46min 22s

In [51]:
%%time
create_csv('aboverm_per_nhblk15')

CPU times: user 1h 45min 4s, sys: 7min 10s, total: 1h 52min 14s
Wall time: 1h 40min 12s

In [52]:
%%time
create_csv('aboverm_per_asian15')

CPU times: user 1h 48min 4s, sys: 7min 52s, total: 1h 55min 56s
Wall time: 1h 43min 18s

In [53]:
%%time
create_csv('aboverm_density15')

CPU times: user 1h 48min 27s, sys: 7min 53s, total: 1h 56min 21s
Wall time: 1h 43min 40s

In [54]:
%%time
create_csv('aboverm_per_hisp15')

CPU times: user 1h 46min 54s, sys: 7min 35s, total: 1h 54min 30s
Wall time: 1h 42min 9s

In [55]:
%%time
create_csv('LI_under80AMI')

CPU times: user 1h 47min 39s, sys: 7min 48s, total: 1h 55min 28s
Wall time: 1h 42min 59s

In [56]:
%%time
create_csv('HI_above120AMI')

CPU times: user 1h 46min 25s, sys: 7min 32s, total: 1h 53min 58s
Wall time: 1h 41min 41s

In [57]:
%%time
create_csv('MI_80_120AMI')

CPU times: user 1h 48min 9s, sys: 7min 33s, total: 1h 55min 43s
Wall time: 1h 43min 18s

In [58]:
%%time
create_csv('disp_type')

CPU times: user 1h 47min 47s, sys: 7min 38s, total: 1h 55min 25s
Wall time: 1h 42min 50s

In [59]:
%%time
aboverm_per_col15.to_csv('aboverm_per_col15_*.csv')

CPU times: user 53min 8s, sys: 3min 37s, total: 56min 46s
Wall time: 50min 41s

['aboverm_per_col15_0.csv']

In [60]:
[i + '_0.csv' for i in demo_var.columns if i != 'home_tract']

['aboverm_per_col15_0.csv',
 'aboverm_per_nonwhite15_0.csv',
 'aboverm_empd14_0.csv',
 'aboverm_per_nhblk15_0.csv',
 'aboverm_per_asian15_0.csv',
 'aboverm_density15_0.csv',
 'aboverm_per_hisp15_0.csv',
 'disp_type_0.csv',
 'LI_under80AMI_0.csv',
 'HI_above120AMI_0.csv',
 'MI_80_120AMI_0.csv']

## OUTPUT FILE
Creating the final result table. 

Labeling the columns with its correct name

Dividing the count by total tweets to get percentages

In [7]:
col15 = pd.read_csv('aboverm_per_col15_0.csv') # 0 and 1
nonwhite = pd.read_csv('aboverm_per_nonwhite15_0.csv') # 0 and 1
empd = pd.read_csv( 'aboverm_empd14_0.csv') # 0 and 1
nhblk = pd.read_csv( 'aboverm_per_nhblk15_0.csv') # 0 and 1
asian = pd.read_csv('aboverm_per_asian15_0.csv') # 0 and 1
density = pd.read_csv('aboverm_density15_0.csv') # 0 and 1
hisp = pd.read_csv('aboverm_per_hisp15_0.csv') # 0 and 1
disptype = pd.read_csv('disp_type_0.csv') # 9 variables
under80 = pd.read_csv('LI_under80AMI_0.csv') # 0 and 1
above120 = pd.read_csv('HI_above120AMI_0.csv') # 0 and 1
MI = pd.read_csv('MI_80_120AMI_0.csv') # 0 and 1
totaltweets= pd.read_csv('new_nn_bayarea_totaltweets_0.csv')

In [8]:
MI = MI[['tract', '1']]
totaltweets = totaltweets[['tract', 'id']].rename({'id': 'total_tweets'}, axis = 1)
MI = MI.rename({'1': 'ct_othertweets_MI_80_120AMI'}, axis =1)
above120 = above120[['tract', '1']].rename({'1': 'ct_othertweets_HI_above_120AMI'}, axis =1)
under80 = under80[['tract', '1']].rename({'1': 'ct_othertweets_LI_under80AMI'}, axis =1)
disptype.columns = ['tract'] + ['ct_othertweets_' + k for k in disptype.columns if k != 'tract']
hisp = hisp.rename({'1.0': 'ct_othertweets_aboverm_per_hisp15', 
                   '0.0': 'ct_othertweets_underm_per_hisp15'}, axis =1)
density = density.rename({'1': 'ct_othertweets_aboverm_density15', 
                   '0': 'ct_othertweets_underm_density15'}, axis =1)
asian = asian.rename({'1.0': 'ct_othertweets_aboverm_per_asian15',
                     '0.0': 'ct_othertweets_underm_per_asian15'}, axis =1)
nhblk = nhblk.rename({'1.0': 'ct_othertweets_aboverm_per_nhblk15',
                     '0.0': 'ct_othertweets_underm_per_nhblk15'}, axis = 1)
empd = empd.rename({'1': 'ct_othertweets_aboverm_empd14', 
                   '0': 'ct_othertweets_underm_empd14'}, axis = 1)
nonwhite = nonwhite.rename({'1.0': 'ct_othertweets_aboverm_per_nonwhite15',
                     '0.0': 'ct_othertweets_underm_per_nonwhite15'}, axis = 1)
col15 = col15.rename({'1.0': 'ct_othertweets_aboverm_per_col15',
                     '0.0': 'ct_othertweets_underm_per_col15'}, axis =1)

In [9]:
twitter_demo_sf= MI.merge(above120, on = 'tract', how = 'inner').merge(
under80, on = 'tract', how ='inner').merge(
disptype, on ='tract', how ='inner').merge(
hisp, on ='tract', how ='inner').merge(
density, on ='tract', how ='inner').merge(
asian, on ='tract', how = 'inner').merge(
nhblk, on = 'tract', how ='inner').merge(
empd, on ='tract', how ='inner').merge(
nonwhite, on ='tract', how = 'inner').merge(
col15, on ='tract', how = 'inner').merge(
totaltweets, on = 'tract', how = 'inner')

In [10]:
twitter_demo_sf = twitter_demo_sf.fillna(0)
twitter_demo_sf['total_nonneighbortweets'] = twitter_demo_sf['ct_othertweets_HI_above_120AMI'] + twitter_demo_sf['ct_othertweets_LI_under80AMI'] + twitter_demo_sf['ct_othertweets_MI_80_120AMI']
for i in twitter_demo_sf.columns:
    if i not in ['total_nonneighbortweets', 'tract']:
        twitter_demo_sf['%_'+ i[2:len(i)]] = twitter_demo_sf[i]/twitter_demo_sf['total_nonneighbortweets']

In [73]:
twitter_demo_sf.to_csv('Twitter_NonNeighborBayArea_demog_10_23.csv')

In [16]:
#Tweets from outside of Bay Area in each tract
outside = pd.read_csv('nnfromoutside_bayarea_totaltweets_0.csv')

## Filtering raw data for Alameda County

In [4]:
sf_nn = pd.read_csv('sfbay_13county_nearest_neigbbor_new.csv')
alameda = []
for i in sf_nn['SRC_GEOID'].unique():
    if 6001000000 <= i & i < 6002000000:
        alameda.append(i)

In [5]:
alamedatwitter = df[(df['tract'] < 6002000000.0) & (df['tract'] >= 6001000000.0)]

In [ ]:
%%time
alamedatwitter.to_csv('alamedatwitter_*.csv')

## Understanding Data with SF Profiles
Includes user description, text, username, etc

In [3]:
%%time
pro = [str(k) for k in list(Path('/scratch/public/catherinebui/SF Profiles').glob('*.csv'))]
p0= pd.read_csv(pro[0])
# p0 = p0.merge(sf_o, on = 'id', how = 'inner')
# p0 =  p0[(p0['tract'] < 6002000000.0) & (p0['tract'] >= 6001000000.0)]

CPU times: user 15.4 s, sys: 944 ms, total: 16.3 s
Wall time: 16.5 s

In [41]:
np.count_nonzero(p0.groupby(
    ['u_id', 'u_location']).aggregate(
    {'u_id' : 'count'}).rename(
    {'u_id': 'count'}, axis =1).reset_index().groupby(
    'u_id').count()['u_location'] > 1)

962

In [44]:
p0.groupby(
    ['u_id', 'lat', 'lon']).aggregate(
    {'u_id' : 'count'}).rename(
    {'u_id': 'count'}, axis =1).reset_index()

               u_id        lat         lon  count
0                12  37.616989 -122.391838      1
1                12  37.781066 -122.405316      1
2                12  37.781591 -122.405985      1
3                12  37.781970 -122.406161      1
4                12  37.820302 -122.455271      1
5                15  37.616424 -122.386279      1
6                15  37.760643 -122.421317      1
7                15  37.766449 -122.455650      1
8                15  37.766588 -122.455368      1
9                15  37.770292 -122.440457      4
10               15  37.781004 -122.402675      1
11               15  37.796949 -122.399713      1
12               15  37.905523 -122.547384      1
13               18  37.770292 -122.440457      1
14               18  37.786441 -122.405502      1
15               18  37.786456 -122.405579      1
16               18  37.786462 -122.405582      1
17               18  37.786488 -122.405523      1
18               18  37.786517 -122.405543      1
19               18  37.805280 -122.403104      1
20               18  37.826323 -122.437410      1
21               18  37.928824 -122.531472      1
22               18  37.928967 -122.531303      1
23               18  37.945737 -122.520096      1
24               21  37.414577 -122.149790      1
25               21  37.454284 -122.113938      1
26               21  37.615761 -122.387910      1
27               21  37.735392 -122.506313      2
28               21  37.773532 -122.425698      2
29               21  37.777250 -122.416983      4
...             ...        ...         ...    ...
1059727  1317248294  37.975106 -121.687886      1
1059728  1317293076  37.009209 -121.589848      1
1059729  1317501361  37.613376 -122.384502      1
1059730  1317501361  37.615489 -122.386501      1
1059731  1317501361  37.616233 -122.388070      2
1059732  1317501361  37.620118 -122.398595      1
1059733  1317501361  37.686918 -122.469813      2
1059734  1317705565  37.750362 -122.202975      1
1059735  1317705565  37.750420 -122.203095      1
1059736  1317766225  38.310075 -122.338579      1
1059737  1317800263  37.785881 -122.435018      1
1059738  1317812816  37.781935 -122.431519      7
1059739  1317812816  37.786329 -122.438921      1
1059740  1317894360  37.879682 -122.098608      1
1059741  1317914035  37.529507 -122.008823      1
1059742  1318112684  37.964967 -121.345326      1
1059743  1318112684  37.965137 -121.345211      1
1059744  1318694557  37.763998 -122.238008      1
1059745  1318694557  37.764003 -122.238009      1
1059746  1318694557  37.764011 -122.237999      1
1059747  1318949996  38.561663 -121.450070      4
1059748  1318992637  37.513118 -122.467290      2
1059749  1319008304  37.543829 -121.979681      1
1059750  1319095513  38.579760 -121.304801      2
1059751  1319132833  37.717351 -121.901730      1
1059752  1319546280  37.797358 -122.206895      1
1059753  1319546280  37.797383 -122.206764      1
1059754  1319546280  37.797453 -122.206755      1
1059755  1319546280  37.797475 -122.206988      1
1059756  1319546280  37.797624 -122.206588      1

[1059757 rows x 4 columns]

In [45]:
p0.groupby(
    ['lat', 'lon']).aggregate(
    {'u_id' : 'count'}).rename(
    {'u_id': 'count'}, axis =1).reset_index()

              lat         lon  count
0       36.801265 -121.681091      1
1       36.801274 -121.665722      1
2       36.801394 -121.680897      1
3       36.801629 -121.786155      1
4       36.801647 -121.659535      1
5       36.801733 -121.660195      1
6       36.801770 -121.788705      1
7       36.801834 -121.665878      1
8       36.801944 -121.727119      1
9       36.801980 -121.661300      1
10      36.802091 -121.665620      1
11      36.802435 -121.678357      1
12      36.802446 -121.639175      1
13      36.802511 -121.665998      1
14      36.802599 -121.666243      1
15      36.802758 -121.655668      1
16      36.802872 -121.655036      1
17      36.802903 -121.787279      1
18      36.802910 -121.787216      2
19      36.802939 -121.661412      1
20      36.803116 -121.787527      1
21      36.803123 -121.667916      1
22      36.803153 -121.787117      8
23      36.803160 -121.666830      1
24      36.803200 -121.787000      1
25      36.803284 -121.788256      1
26      36.803338 -121.788429      1
27      36.803397 -121.651519      1
28      36.803417 -121.626653      1
29      36.803469 -121.654067      1
...           ...         ...    ...
954366  38.963005 -122.640836      1
954367  38.963062 -122.640969      1
954368  38.963251 -122.023968      2
954369  38.963481 -121.337040      1
954370  38.963563 -122.630552      2
954371  38.964136 -121.107208      1
954372  38.964182 -121.107183      1
954373  38.964213 -122.652448      1
954374  38.964214 -121.106995      1
954375  38.964263 -122.642214      4
954376  38.965072 -122.837263      3
954377  38.965218 -122.025745      1
954378  38.965341 -121.334970      1
954379  38.965521 -121.355784      1
954380  38.965617 -121.606701      1
954381  38.965815 -121.376477      1
954382  38.965938 -121.399795      1
954383  38.965953 -121.399854      1
954384  38.965956 -121.399780      1
954385  38.965967 -121.399878      1
954386  38.966000 -122.652000      1
954387  38.966039 -121.551619      1
954388  38.966184 -122.026242      1
954389  38.966208 -121.607058      1
954390  38.966230 -121.399695      1
954391  38.966605 -121.400070      1
954392  38.966725 -121.489649     10
954393  38.966757 -121.489906     13
954394  38.966770 -121.374937      1
954395  38.966789 -121.489885      6

[954396 rows x 3 columns]

In [5]:
p1=pd.read_csv(pro[1])
# p1['id'] = p1['id'].astype(float)
# p1 = p1.merge(sf_o, on = 'id', how = 'inner')
# # p1 =  p1[(p1['tract'] < 6002000000.0) & (p1['tract'] >= 6001000000.0)]

p2=pd.read_csv(pro[2])
# p2['id'] = p2['id'].astype(float)
# p2 = p2.merge(sf_o, on = 'id', how = 'inner')
# p2 =  p2[(p2['tract'] < 6002000000.0) & (p2['tract'] >= 6001000000.0)]

In [6]:
p1

,id,u_id,lat,lon,created_at,type,place_type,u_created_at,u_followers_count,u_location,u_lang,u_statuses_count,u_name,u_screen_name,u_description,urls,text
0,4.978132e+17,269555096,36.959819,-122.027553,1407522882000,llp,city,1300669446000,106,NaN,en,5457,Arianne Nova,ariannenova,I hate people,NaN,@trentistweeting 💖
1,4.978132e+17,744492187,37.783333,-122.416667,1407522885000,llp,city,1344402974000,117,"Los Angeles, CA",en,2511,Jasen Martin,jasenmvaca,Photographer,NaN,"🌁 @ San Francisco, CA http://t.co/MmvHR9enIa"
2,4.978132e+17,22708540,38.555097,-121.429662,1407522888000,llp,city,1236127628000,24887,"Sacramento, CA",en,8954,HoppyBrewing,HoppyBrewing,Great Food • Awesome Beer • Cool People!!!,NaN,Hi #Sacramento! :-) Here's a pic of 2days lunc...
3,4.978131e+17,293143885,38.900242,-121.322048,1407522877000,llp,city,1304542170000,263,NaN,en,19177,ΤΣΦ,joshvp4,12/01-forever,NaN,Stupid ass shit man. Who would buy a whole new...
4,4.978131e+17,858428251,38.342015,-121.964636,1407522868000,llp,city,1349199465000,257,Jevan & Kamie,en,22995,MORE TRASH,lifterofweight,Kevan//Heavy riffs//heavy weight//depth before...,NaN,And just threw away ten bucks bc I forgot abou...
5,4.978132e+17,2236904258,37.748598,-122.168636,1407522878000,llp,city,1386557664000,246,NaN,en,21406,A9K__,ANKatoa,"Oakland, CA",NaN,Dayum ugly fobby ass just kilt my effin day! S...
6,4.978131e+17,23366474,37.850235,-122.270612,1407522871000,llp,city,1236552772000,1417,"Oakland, California",en,11366,Jimi Devine,JimiDevine,"Cannabis, Stand Up Comedy, & Politics. All RT...",NaN,Every Olsen twins straight to VHS movie. #Movi...
7,4.978132e+17,1330392194,37.712584,-122.020670,1407522891000,llp,city,1365209950000,753,NaN,en,20042,Daddy Sav✨,amazing_sav,Life is good✊ but my pussy better || ig: @amaz...,NaN,@junior98ribas I'm not legal either I'm just s...
8,4.978132e+17,141618790,37.616424,-122.386279,1407522895000,llp,admin,1273331487000,237,"Santiago, Chile",en,17809,Camilo Pedrero,Cdmas2,"Living life, working on what I love at W Santi...",NaN,In transit ... back home (@ San Francisco Inte...
9,4.978132e+17,738159110,38.293474,-122.459071,1407522899000,llp,city,1344150336000,107,"Napa, CA",en,880,StrawberrieFox,StrawberrieFox,"Just me, 30 yrs old, chef, CIAGreystone studen...",NaN,#avocadoeggtoast @ Sunflower Caffe Sonoma Vall...
10,4.978131e+17,25251876,37.770292,-122.440457,1407522866000,p,city,1237444982000,356,"San Mateo, Calif.",en,18088,Frisco Del Rosario,frdelrosario,"Appium/Selenium scripter, chess author and tea...",NaN,"@thehighsign If I were Bradley Cooper, I'd put..."
11,4.978132e+17,307220437,37.702844,-122.472836,1407522879000,llp,city,1306653619000,124,"San Francisco, CA",en,35481,Abdullah,AAlnajdii,"No pain no gain!\nStudent at USF, Peace & Conf...",NaN,الاسك فر مخي ولا عرفت له
12,4.978133e+17,2428261014,38.055063,-121.373688,1407522908000,llp,admin,1396670799000,230,NaN,en,282,Corinne Haas,c__haas,Don't be afraid to get your halo dirty,NaN,"Trenton: ""If you meet your future husband in c..."
13,4.978135e+17,1226411449,36.971813,-121.951605,1407522962000,llp,city,1362014344000,435,NaN,en,6000,ryan,thelittleking23,Cause my life is Dope & I do Dope shit.b,NaN,It's been a real summer!
14,4.978138e+17,19048998,37.806529,-122.420654,1407523034000,llp,city,1232069132000,152,Bay Area,en,2479,David Artale,dartale2,#zombie assassin; #biophiliast - corporate artist,NaN,Irish coffees to kick off the day (@ Buena Vis...
15,4.978138e+17,25043849,37.429428,-121.909273,1407523031000,llp,city,1237362812000,345,bay area,en,24341,kimberly ann paras,kimberparas,HYPE.,NaN,“@Forbes: Dallas is # 10 on our list of Americ...
16,4.978138e+17,2252884777,38.327160,-122.329592,1407523034000,llp,city,1387422131000,336,NaN,en,10412,Edgar,ragde__,TEAM USA --- Golden St. Warriors #DubNation \\...,NaN,@JuanJoelVargas oh
17,4.978138e+17,1684840094,37.707722,-121.419050,1407523023000,llp,city,1376972352000,486,NaN,en,4909,Leezus,leebrewer_17,NaN,NaN,hate this 😂
18,4.978139e+17,44553004,36.965810,-122.025518,1407523050000,llp,city,1244092939000,168,Santa Cruz,en,10766,Patrick Perez,patchyskies,"hey I'm Patrick, also known as Patch! And I'm ...",NaN,@Kiesza ha!
19,4.978140e+17,325110982,37.471234,-121.141563,1407523085000,llp,city,1309201941000,454,Northern California,en,37860,Ty Dolla $ign,T_weez35,♌️ 08/05/1995 Phs C/o 2013,NaN,Boy im bout my business on business
20,4.978140e+17,321581498,37.776591,-122.429696,1407523073000,llp,city,1308687077000,1408,Oakland,en,85764,SLUM,3rdEyeHI,My Coworker said it was bitches on Twitter so ...,NaN,Yall better wake the fuck up before its too late
21,4.978140e+17,331463447,37.769407,-122.496187,1407523081000,llp,city,1310106491000,179,NaN,en,6337,Ella Bella✨,ellamscott,"Haters gonna hate, tomatoes gonna tomate, pota...",NaN,@_hoodrat666 we'll party for you😊
22,4.978142e+17,430389830,38.677566,-121.772346,1407523128000,llp,city,1323228615000,220,NaN,en,17533,Chasing Sunshine,Tiinanichole,A head filled with flowers and hands filled wi...,NaN,Last night was craZy
23,4.978144e+17,183322216,37.703609,-121.865853,1407523178000,llp,admin,1282847435000,296,Pittsburgh,en,7708,Goldstar Pittsburgh,GoldstarPgh,For the obsessively compulsive fans in Pittsbu...,NaN,New Event: Desi Comedy Fest @ Vito's Express (...
24,4.978144e+17,495688079,38.019450,-121.333280,1407523173000,llp,city,1329547244000,609,"Stockton, California",en,32264,Maggie Gonzalez,maggiexgonzalez,Big dreams // Good music,NaN,@aceofspadessac I GOT VIP THANK U FOR RE STOCK...
25,4.978144e+17,448509224,38.102454,-122.256354,1407523172000,llp,city,1325040074000,1419,Vallejo Ca ✊,en,57070,redrumxo✨,naaajx,#OneLove✨,NaN,“@ILongDickHoes_: I swear to god it's not hard...
26,4.978146e+17,251683857,37.533214,-122.251489,1407523224000,llp,city,1297616446000,944,"Redwood Shores, CA",en,9039,Jack,j4ck96,Washington State Cougars #rilsquad #pac12 #cal...,NaN,Rory needs to calm down with these leads he's ...
27,4.978146e+17,34738241,37.331083,-121.889513,1407523226000,llp,city,1240522587000,1667,"San Jose, CA",en,4413,Goldstar San Jose,GoldstarSanJose,For the obsessively compulsive fans in San Jos...,NaN,New Event: Opera Bravura @ Montgomery Theater ...
28,4.978149e+17,2166075008,38.050107,-121.389840,1407523305000,llp,admin,1383198964000,841,"Stockton, California",en,8554,FRANNY,xFrancisRoque,1995 - Forever | #YB,NaN,“@TR_647: I was too turnt yesterday 😕 http://t...
29,4.978149e+17,1589692776,37.774024,-122.420599,1407523299000,llp,city,1373673888000,1,"San Francisco, CA",en,82297,SF311 Reports,SF311Reports,This is account is not monitored and is used t...,NaN,Opened Graffiti request via android at 1631 Ma...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2308045,5.062897e+17,295427556,38.431317,-122.745440,1409543840000,llp,city,1304902220000,156,paha sapa,en,26143,hannah ☼,han__fran,dont take shit from a cat person,NaN,even landlocked lovers yearn for a sea like na...
2308046,5.062897e+17,2249669550,37.903039,-122.278200,1409543855000,llp,city,1387247715000,120,"Bay Area, CA",en,897,Gabbyyyy,yah_bish_gabby,who is you✨\n•E.H❤️•D.H❤️•Whitesider❤\n•0/12,NaN,@GabbyMars uhm excuse me tf you talking bout!!...
2308047,5.062898e+17,574840917,37.416692,-121.872507,1409543868000,llp,city,1336508118000,634,NaN,en,11288,ChronicGoon,Chronic_Goon,West Side Get Money Gang,NaN,Boring Sunday Night
2308048,5.062898e+17,767969280,37.710871,-121.178768,1409543875000,llp,admin,1345399334000,361,NaN,en,8358,A,aneicamartinez,sunflowers & candles,NaN,“@RelatableQuote: Who else gets cute goodnight...
2308049,5.062898e+17,992204228,37.609758,-122.429264,1409543870000,llp,city,1354759726000,177,in yo momz closet,en,5028,Joseph Albert Fields,Papa_J_Pickles,"A man chooses, a slave obeys",NaN,@Mannahleneee fuck you
2308050,5.062900e+17,304815470,37.717639,-122.480906,1409543911000,llp,city,1306298651000,24,san francisco,en,84,ZhangTantantan,Tanebecca,U know what i am hahaha,NaN,#FranklinandBash the kiss http://t.co/VcLbZuuDRN
2308051,5.062900e+17,13281492,37.796402,-122.403807,1409543908000,llp,city,1202564770000,1835,Belgium,en,2145,Pieterjan Bouten,pieterjan,Tech Entrepreneur. Co-Founder and CEO of Showp...,NaN,Nav artikel in @tijd over mobiliteit mailtje g...
2308052,5.062900e+17,743922486,38.014225,-121.362942,1409543925000,llp,city,1344380210000,576,Cali ☀️,en,26898,ⓜ & ⓜ,malia_maningo,Has anyone shared a coke with me yet????,NaN,@domhunt18 :-)
2308053,5.062900e+17,737812603,37.339972,-122.061321,1409543919000,llp,city,1344132378000,70,"San Jose, CA",en,1514,Chantel D,hellochantii,I'm peachy keen & the bee's knees. ∞ ♡ Instagr...,NaN,my new fave #Luisi #moscatodasti 😍 @ lost in l...
2308054,5.062901e+17,348950192,37.680967,-122.061589,1409543949000,llp,city,1312532553000,397,NaN,en,12133,Queen_ Leesh,Simply_Leesh,Blessed . Poetic Vibes flowing through my vein...,NaN,“@briaaaaaaaaaaa: @Simply_Leesh 😂😂😂😂 he was al...
2308055,5.062902e+17,1526004710,37.360169,-122.027918,1409543975000,llp,city,1371506437000,208,"Sunnyvale, Ca",en,6658,King Migs,phengthang,Everything has a silver lining,NaN,First Jennifer Lawrence NOW Kate Upton???!!! T...
2308056,5.062902e+17,172987303,38.272720,-122.679222,1409543972000,llp,city,1280547235000,145,Stockton CA,en,9254,Richard Valenzuela,valrich79,kicking against the goads,NaN,"@RealRaider2055 @AsherMathews @Jerrymcd Agree,..."
2308057,5.062903e+17,120774921,37.890383,-122.060156,1409543995000,p,city,1267971482000,510,"Depok,Jakarta,Palu",en,51280,Zulfikar Rizki,ijul_fikar,a Copy-Paste-Edit Web Programmer | Milannisti,NaN,My #NurulWish mylaff :))))
2308058,5.062903e+17,389866849,37.718162,-122.451210,1409543987000,llp,city,1318476461000,46,San francisco,en,194,turki ghonaim,turkighonaim,"I born in NOV 1992 , love what you do ... To d...",NaN,as above so below is the worst movie ever 👎
2308059,5.062896e+17,1253253492,37.911965,-122.306138,1409543829000,llp,city,1362798542000,211,Support the brand,en,1601,Myke,jerez510,DiamondLife | CEO of OutLook.ClothingSF | take...,NaN,Since when does pac sun carry TH? 😒
2308060,5.062898e+17,454308883,37.523772,-122.267141,1409543866000,llp,city,1325625440000,341,NaN,en,813,morgan bennett,morgancbennett,NaN,NaN,youre just not a nice person and that makes me...
2308061,5.062898e+17,38548640,38.563203,-121.751918,1409543865000,llp,city,1241739329000,304,Orange County,en,16955,WhiteChocolate,bigggtrev,For Basketball clinics: See me in the Gym. A R...,NaN,@PushazInkBoiii boo😴😴
2308062,5.062898e+17,562524394,37.715291,-121.084408,1409543873000,llp,city,1335320720000,445,lrv,en,17856,jennylou,jeennnyy_,✨SV | Fremont HS | ✨,NaN,It's hella hot here &amp; I just wanna go home 😡
2308063,5.062899e+17,2206326103,37.244815,-121.917177,1409543887000,llp,city,1385006861000,198,NaN,en,578,jordan lacey☯,jordanlacey26,Nothing but good vibes,NaN,When my sis and I snapchat each other😈 http://...
2308064,5.062899e+17,2425155572,37.462688,-122.230897,1409543895000,llp,city,1396506518000,182,California,en,5159,Niclitoris,nicolebabes44,ohoh snapchat: nicole_babes,NaN,I have the best napping playlist evr hmu if u d
2308065,5.062899e+17,710248182,37.965187,-121.986349,1409543893000,llp,city,1342939937000,693,925,en,7728,zee❥,ZKamin,xoxo,NaN,👽
2308066,5.062900e+17,624001561,38.674618,-121.240905,1409543906000,llp,city,1341169264000,796,NaN,en,29567,Drax,Rae_Cherry,No days off. #KingMe,NaN,Some weird ass people in fair oaks😂
2308067,5.062901e+17,433045215,37.765501,-122.452573,1409543932000,llp,city,1323484640000,12302,"San Francisco, CA",ar,61755,طويل العمر,bdr_sf,احب المواطنين ولست منهم || هلالي ارسنالي ||,NaN,@NF62 @hatemOtb \n\nوروني اذا وروكم
2308068,5.062901e+17,704949296,38.293391,-121.981952,1409543930000,llp,city,1342699939000,424,Stuck in Cali,en,10350,Trisha Cris.,Thatsotrishh,16 x Jeremiah 29:11 x Christ Above All,NaN,I wunnuh be da very best lyk no one ever wwwuuz ~
2308069,5.062901e+17,24884955,38.337842,-122.690044,1409543943000,llp,city,1237298519000,174,"Rohnert Park, CA",en,5067,daniel laguinto,dlaguinto,NaN,NaN,No Sunday blues tonight... #threedayweekend
2308070,5.062902e+17,337538237,38.786570,-121.282742,1409543954000,llp,city,1310967227000,283,California,en,6577,Charles R.Ousley,MrSkoringo,"VA, Abridger, Chill guy. Follow to keep tabs o...",NaN,@GreatDetective0 I'm.more genuinely curious.
2308071,5.062902e+17,63913765,38.426296,-121.437724,1409543959000,llp,city,1249708929000,706,NaN,en,18443,telle❁,shaaaantelle,GOD IS MY HOMIE,NaN,one time me and Shawn were fighting and his bi...
2308072,5.062902e+17,238055666,37.760600,-122.391070,1409543959000,llp,city,1294990543000,183,San Francisco,en,1290,Radu Ranga,raduranga,"Cyclist, designer, photographer, marketing and...",NaN,bmw @bmwusa #bmw #bmwusa #sanfrancisco @ Dogpa...
2308073,5.062903e+17,549760617,38.630941,-121.407113,1409543984000,llp,city,1334018686000,184,NaN,en,5380,Forrest_22,ForrestNumber5,Sad boys ~2014,NaN,I BALL HARD CHUUUUURRRRcccchhhh
2308074,5.062903e+17,586303011,37.726895,-122.422141,1409543983000,llp,city,1337571993000,244,sfc,en,9919,Deborah.,deborahhxo,NaN,NaN,Just realized I haven't ate anything all day

In [6]:
%%time
p3=pd.read_csv(pro[3])
# p3['id'] = p3['id'].astype(float)
# p3 = p3.merge(sf_o, on = 'id', how = 'inner')
# p3 =  p3[(p3['tract'] < 6002000000.0) & (p3['tract'] >= 6001000000.0)]

p4=das.read_csv(pro[4])
# p4['id'] = p4['id'].astype(float)
# p4 = p4.merge(sf_o, on = 'id', how = 'inner')
# p4 =  p4[(p4['tract'] < 6002000000.0) & (p4['tract'] >= 6001000000.0)]

CPU times: user 12.7 s, sys: 672 ms, total: 13.3 s
Wall time: 13.6 s

In [7]:
p5=das.read_csv(pro[5])
# p5['id'] = p5['id'].astype(float)
# p5 = p5.merge(sf_o, on = 'id', how = 'inner')
# p5 =  p5[(p5['tract'] < 6002000000.0) & (p5['tract'] >= 6001000000.0)]

p6=pd.read_csv(pro[6], encoding='iso-8859-1')
# p6 = p6.merge(sf_o, on = 'id', how = 'inner')
# p6 =  p6[(p6['tract'] < 6002000000.0) & (p6['tract'] >= 6001000000.0)]

In [8]:
p7=pd.read_csv(pro[7], encoding='iso-8859-1')
# p7['id'] = p7['id'].astype(float)
# p7 = p7.merge(sf_o, on = 'id', how = 'inner')
# p7 =  p7[(p7['tract'] < 6002000000.0) & (p7['tract'] >= 6001000000.0)]

p8=pd.read_csv(pro[8])
# p8['id'] = p8['id'].astype(float)
# p8 = p8.merge(sf_o, on = 'id', how = 'inner')
# p8 =  p8[(p8['tract'] < 6002000000.0) & (p8['tract'] >= 6001000000.0)]

In [9]:
p9=pd.read_csv(pro[9])
# p9['id'] = p9['id'].astype(float)
# p9 = p9.merge(sf_o, on = 'id', how = 'inner')
# p9 =  p9[(p9['tract'] < 6002000000.0) & (p9['tract'] >= 6001000000.0)]

p10=pd.read_csv(pro[10])
# p10['id'] = p10['id'].astype(float)
# p10 = p10.merge(sf_o, on = 'id', how = 'inner')
# p10 =  p10[(p10['tract'] < 6002000000.0) & (p10['tract'] >= 6001000000.0)]

In [10]:
p11=pd.read_csv(pro[11])
# p11['id'] = p11['id'].astype(float)
# p11 = p11.merge(sf_o, on = 'id', how = 'inner')
# p11 =  p11[(p11['tract'] < 6002000000.0) & (p11['tract'] >= 6001000000.0)]

p12=pd.read_csv(pro[12])
# p12['id'] = p12['id'].astype(float)
# p12 = p12.merge(sf_o, on = 'id', how = 'inner')
# p12 =  p12[(p12['tract'] < 6002000000.0) & (p12['tract'] >= 6001000000.0)]

In [11]:
p13=pd.read_csv(pro[13])
# p13['id'] = p13['id'].astype(float)
# p13 = p13.merge(sf_o, on = 'id', how = 'inner')
# p13 =  p13[(p13['tract'] < 6002000000.0) & (p13['tract'] >= 6001000000.0)]

p14= pd.read_csv(pro[14])
# p14['id'] = p14['id'].astype(float)
# p14 = p14.merge(sf_o, on = 'id', how = 'inner')
# p14 =  p14[(p14['tract'] < 6002000000.0) & (p14['tract'] >= 6001000000.0)]

In [12]:
p15=pd.read_csv(pro[15])
# p15['id'] = p15['id'].astype(float)
# p15 = p15.merge(sf_o, on = 'id', how = 'inner')
# p15 =  p15[(p15['tract'] < 6002000000.0) & (p15['tract'] >= 6001000000.0)]

p16=pd.read_csv(pro[16])
# p16['id'] = p16['id'].astype(float)
# p16 = p16.merge(sf_o, on = 'id', how = 'inner')
# p16 =  p16[(p16['tract'] < 6002000000.0) & (p16['tract'] >= 6001000000.0)]

In [13]:
%%time
p17=pd.read_csv(pro[17])
# p17['id'] = p17['id'].astype(float)
# p17 = p17.merge(sf_o, on = 'id', how = 'inner')
# p17 =  p17[(p17['tract'] < 6002000000.0) & (p17['tract'] >= 6001000000.0)]

p18=pd.read_csv(pro[18])
# p18['id'] = p18['id'].astype(float)
# p18 = p18.merge(sf_o, on = 'id', how = 'inner')
# p18 =  p18[(p18['tract'] < 6002000000.0) & (p18['tract'] >= 6001000000.0)]

CPU times: user 17.5 s, sys: 1.24 s, total: 18.8 s
Wall time: 20.4 s

In [14]:
p19=pd.read_csv(pro[19])
# p19['id'] = p19['id'].astype(float)
# p19 = p19.merge(sf_o, on = 'id', how = 'inner')
# p19 =  p19[(p19['tract'] < 6002000000.0) & (p19['tract'] >= 6001000000.0)]

p20=pd.read_csv(pro[20])
# p20['id'] = p20['id'].astype(float)
# p20 = p20.merge(sf_o, on = 'id', how = 'inner')
# p20 =  p20[(p20['tract'] < 6002000000.0) & (p20['tract'] >= 6001000000.0)]

In [15]:
p21=pd.read_csv(pro[21])
# p21['id'] = p21['id'].astype(float)
# p21 = p21.merge(sf_o, on = 'id', how = 'inner')
# p21 =  p21[(p21['tract'] < 6002000000.0) & (p21['tract'] >= 6001000000.0)]

p22=pd.read_csv(pro[22])
# p22['id'] = p22['id'].astype(float)
# p22 = p22.merge(sf_o, on = 'id', how = 'inner')
# p22 =  p22[(p22['tract'] < 6002000000.0) & (p22['tract'] >= 6001000000.0)]

In [16]:
p23=pd.read_csv(pro[23])
# p23['id'] = p23['id'].astype(float)
# p23 = p23.merge(sf_o, on = 'id', how = 'inner')
# p23 =  p23[(p23['tract'] < 6002000000.0) & (p23['tract'] >= 6001000000.0)]

p24=pd.read_csv(pro[24])
# p24['id'] = p24['id'].astype(float)
# p24 = p24.merge(sf_o, on = 'id', how = 'inner')
# p24 =  p24[(p24['tract'] < 6002000000.0) & (p24['tract'] >= 6001000000.0)]

In [17]:
p25=pd.read_csv(pro[25])
# p25['id'] = p25['id'].astype(float)
# p25 = p25.merge(sf_o, on = 'id', how = 'inner')
# p25 =  p25[(p25['tract'] < 6002000000.0) & (p25['tract'] >= 6001000000.0)]

p26=pd.read_csv(pro[26])
# p26['id'] = p26['id'].astype(float)
# p26 = p26.merge(sf_o, on = 'id', how = 'inner')
# p26 =  p26[(p26['tract'] < 6002000000.0) & (p26['tract'] >= 6001000000.0)]

In [18]:
p27=pd.read_csv(pro[27])
# p27['id'] = p27['id'].astype(float)
# p27 = p27.merge(sf_o, on = 'id', how = 'inner')
# p27 =  p27[(p27['tract'] < 6002000000.0) & (p27['tract'] >= 6001000000.0)]

p28=pd.read_csv(pro[28])
# p28['id'] = p28['id'].astype(float)
# p28 = p28.merge(sf_o, on = 'id', how = 'inner')
# p28 =  p28[(p28['tract'] < 6002000000.0) & (p28['tract'] >= 6001000000.0)]

In [19]:
p29=pd.read_csv(pro[29])
# p29['id'] = p29['id'].astype(float)
# p29 = p29.merge(sf_o, on = 'id', how = 'inner')
# p29 =  p29[(p29['tract'] < 6002000000.0) & (p29['tract'] >= 6001000000.0)]

p30=pd.read_csv(pro[30])
# p30['id'] = p30['id'].astype(float)
# p30 = p30.merge(sf_o, on = 'id', how = 'inner')
# p30 =  p30[(p30['tract'] < 6002000000.0) & (p30['tract'] >= 6001000000.0)]

In [20]:
p31=pd.read_csv(pro[31])
# p31['id'] = p31['id'].astype(float)
# p31 = p31.merge(sf_o, on = 'id', how = 'inner')
# p31 =  p31[(p31['tract'] < 6002000000.0) & (p31['tract'] >= 6001000000.0)]

p32=pd.read_csv(pro[32])
# p32['id'] = p32['id'].astype(float)
# p32 = p32.merge(sf_o, on = 'id', how = 'inner')
# p32 =  p32[(p32['tract'] < 6002000000.0) & (p32['tract'] >= 6001000000.0)]

In [21]:
p33 = pd.read_csv(pro[33])
# p33['id'] = p33['id'].astype(float)
# p33 = p33.merge(sf_o, on = 'id', how = 'inner')
# p33 =  p33[(p33['tract'] < 6002000000.0) & (p33['tract'] >= 6001000000.0)]

p34 = pd.read_csv(pro[34])
# p34['id'] = p34['id'].astype(float)
# p34 = p34.merge(sf_o, on = 'id', how = 'inner')
# p34 =  p34[(p34['tract'] < 6002000000.0) & (p34['tract'] >= 6001000000.0)]

pd.concat([pd.read_csv(pro[i]) for i in np.arange(17, 35, 1)]).to_csv('/scratch/public/catherinebui/prof_17_35.csv')

pd.concat([pd.read_csv(pro[i], encoding = 'iso-8859-1') for i in np.arange(0, 35, 1)]).to_csv('/scratch/public/catherinebui/sf_alameda_twitterprofile.csv')

pd.concat([p0,p1,p2,p3,p4,p5,p6,p7,p8,
          p9,p10,p11,p12,p13,p14,p15,p16,p17, p18,
          p19, p20, p21, p22, p23, p24, p25, p26, p27, p28,
          p29, p30, p31,p32, p33, p34]).to_csv('/scratch/public/catherinebui/sf_alameda_twitterprofile.csv')